# Generated by Django 5.1.2 on 2024-10-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='perguntas',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='email',
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id do material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='questionario_do_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionario', verbose_name='Questionário relacionado'),
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto da Pergunta')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='app.questionario')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto da Alternativa')),
                ('is_correta', models.BooleanField(default=False, verbose_name='É a alternativa correta?')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='app.pergunta')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
            },
        ),
        migrations.DeleteModel(
            name='Perguntas',
        ),
    ]
