# Generated by Django 5.1.2 on 2024-10-19 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.AlterModelOptions(
            name='ocupacao',
            options={'verbose_name': 'Ocupação', 'verbose_name_plural': 'Ocupações'},
        ),
        migrations.AlterModelOptions(
            name='perguntas',
            options={'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AlterModelOptions(
            name='questionario',
            options={'verbose_name': 'Questionário', 'verbose_name_plural': 'Questionários'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='contato',
            name='texto',
            field=models.CharField(max_length=1000, verbose_name='Texto do e-mail'),
        ),
        migrations.AlterField(
            model_name='material',
            name='administrador',
            field=models.CharField(max_length=100, verbose_name='Administrador do material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo do material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do material'),
        ),
        migrations.AlterField(
            model_name='perguntas',
            name='enunciado',
            field=models.CharField(max_length=100, verbose_name='Enunciado da pergunta'),
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='perguntas',
        ),
        migrations.CreateModel(
            name='MaterialAdicionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'verbose_name': 'Material Adicionado',
                'verbose_name_plural': 'Materiais Adicionados',
            },
        ),
        migrations.DeleteModel(
            name='Material_Adicionado',
        ),
        migrations.AddField(
            model_name='questionario',
            name='perguntas',
            field=models.ManyToManyField(to='app.perguntas', verbose_name='Perguntas do questionário'),
        ),
    ]
