# Generated by Django 5.1.2 on 2024-10-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_questionario_perguntas_remove_contato_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialAdicionado',
        ),
    ]
