# Generated by Django 5.1.1 on 2024-09-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_material_adicionado_materialadicionado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='texto',
            field=models.CharField(max_length=1000, verbose_name='Texto do e-mail'),
        ),
    ]
