# Generated by Django 5.1.1 on 2024-09-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_material_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomaterial',
            name='tipo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tipo do material'),
        ),
    ]
