# Generated by Django 5.1.1 on 2024-09-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_tipomaterial_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='tipomaterial',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo do material'),
        ),
    ]
