# Generated by Django 5.1.1 on 2024-09-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_material_tipo_alter_tipomaterial_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoMaterial',
        ),
    ]
